/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherGradesRouteImport } from './routes/teacher.grades'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherChatRouteImport } from './routes/teacher.chat'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentTuitionRouteImport } from './routes/student.tuition'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentRetakeRegistrationRouteImport } from './routes/student.retake-registration'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPaymentResultRouteImport } from './routes/student.payment-result'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentGradesRouteImport } from './routes/student.grades'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCurriculumRouteImport } from './routes/student.curriculum'
import { Route as StudentCourseRegistrationRouteImport } from './routes/student.course-registration'
import { Route as StudentChatRouteImport } from './routes/student.chat'
import { Route as StudentAcademicResultsRouteImport } from './routes/student.academic-results'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminSemestersRouteImport } from './routes/admin.semesters'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPeriodsRouteImport } from './routes/admin.periods'
import { Route as AdminMajorsRouteImport } from './routes/admin.majors'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminHomeroomsRouteImport } from './routes/admin.homerooms'
import { Route as AdminExamSchedulesRouteImport } from './routes/admin.exam-schedules'
import { Route as AdminExamRegistrationsRouteImport } from './routes/admin.exam-registrations'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminClassSectionsRouteImport } from './routes/admin.class-sections'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAcademicResultsRouteImport } from './routes/admin.academic-results'
import { Route as AdminSemestersIndexRouteImport } from './routes/admin.semesters.index'
import { Route as AdminSemestersIdRouteImport } from './routes/admin.semesters.$id'
import { Route as TeacherClassesClassSectionIdStudentsRouteImport } from './routes/teacher.classes.$classSectionId.students'
import { Route as AdminSemestersIdClassesCreateRouteImport } from './routes/admin.semesters.$id_.classes.create'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradesRoute = TeacherGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherChatRoute = TeacherChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTuitionRoute = StudentTuitionRouteImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRetakeRegistrationRoute =
  StudentRetakeRegistrationRouteImport.update({
    id: '/retake-registration',
    path: '/retake-registration',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentResultRoute = StudentPaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCurriculumRoute = StudentCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCourseRegistrationRoute =
  StudentCourseRegistrationRouteImport.update({
    id: '/course-registration',
    path: '/course-registration',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentChatRoute = StudentChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAcademicResultsRoute = StudentAcademicResultsRouteImport.update({
  id: '/academic-results',
  path: '/academic-results',
  getParentRoute: () => StudentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSemestersRoute = AdminSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeriodsRoute = AdminPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMajorsRoute = AdminMajorsRouteImport.update({
  id: '/majors',
  path: '/majors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeroomsRoute = AdminHomeroomsRouteImport.update({
  id: '/homerooms',
  path: '/homerooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamSchedulesRoute = AdminExamSchedulesRouteImport.update({
  id: '/exam-schedules',
  path: '/exam-schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamRegistrationsRoute = AdminExamRegistrationsRouteImport.update({
  id: '/exam-registrations',
  path: '/exam-registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassSectionsRoute = AdminClassSectionsRouteImport.update({
  id: '/class-sections',
  path: '/class-sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicResultsRoute = AdminAcademicResultsRouteImport.update({
  id: '/academic-results',
  path: '/academic-results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSemestersIndexRoute = AdminSemestersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSemestersRoute,
} as any)
const AdminSemestersIdRoute = AdminSemestersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSemestersRoute,
} as any)
const TeacherClassesClassSectionIdStudentsRoute =
  TeacherClassesClassSectionIdStudentsRouteImport.update({
    id: '/$classSectionId/students',
    path: '/$classSectionId/students',
    getParentRoute: () => TeacherClassesRoute,
  } as any)
const AdminSemestersIdClassesCreateRoute =
  AdminSemestersIdClassesCreateRouteImport.update({
    id: '/$id_/classes/create',
    path: '/$id/classes/create',
    getParentRoute: () => AdminSemestersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exam-registrations': typeof AdminExamRegistrationsRoute
  '/admin/exam-schedules': typeof AdminExamSchedulesRoute
  '/admin/homerooms': typeof AdminHomeroomsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/semesters': typeof AdminSemestersRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payment-result': typeof StudentPaymentResultRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/semesters/$id': typeof AdminSemestersIdRoute
  '/admin/semesters/': typeof AdminSemestersIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
  '/admin/semesters/$id/classes/create': typeof AdminSemestersIdClassesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exam-registrations': typeof AdminExamRegistrationsRoute
  '/admin/exam-schedules': typeof AdminExamSchedulesRoute
  '/admin/homerooms': typeof AdminHomeroomsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payment-result': typeof StudentPaymentResultRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/semesters/$id': typeof AdminSemestersIdRoute
  '/admin/semesters': typeof AdminSemestersIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
  '/admin/semesters/$id/classes/create': typeof AdminSemestersIdClassesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-results': typeof AdminAcademicResultsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/class-sections': typeof AdminClassSectionsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/exam-registrations': typeof AdminExamRegistrationsRoute
  '/admin/exam-schedules': typeof AdminExamSchedulesRoute
  '/admin/homerooms': typeof AdminHomeroomsRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/majors': typeof AdminMajorsRoute
  '/admin/periods': typeof AdminPeriodsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/semesters': typeof AdminSemestersRouteWithChildren
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/users': typeof AdminUsersRoute
  '/student/academic-results': typeof StudentAcademicResultsRoute
  '/student/chat': typeof StudentChatRoute
  '/student/course-registration': typeof StudentCourseRegistrationRoute
  '/student/curriculum': typeof StudentCurriculumRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/payment-result': typeof StudentPaymentResultRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/retake-registration': typeof StudentRetakeRegistrationRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tuition': typeof StudentTuitionRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/chat': typeof TeacherChatRoute
  '/teacher/classes': typeof TeacherClassesRouteWithChildren
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/grades': typeof TeacherGradesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
  '/admin/semesters/$id': typeof AdminSemestersIdRoute
  '/admin/semesters/': typeof AdminSemestersIndexRoute
  '/teacher/classes/$classSectionId/students': typeof TeacherClassesClassSectionIdStudentsRoute
  '/admin/semesters/$id_/classes/create': typeof AdminSemestersIdClassesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/exam-registrations'
    | '/admin/exam-schedules'
    | '/admin/homerooms'
    | '/admin/knowledge'
    | '/admin/majors'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/rooms'
    | '/admin/semesters'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/payment-result'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/admin/semesters/$id'
    | '/admin/semesters/'
    | '/teacher/classes/$classSectionId/students'
    | '/admin/semesters/$id/classes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/exam-registrations'
    | '/admin/exam-schedules'
    | '/admin/homerooms'
    | '/admin/knowledge'
    | '/admin/majors'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/rooms'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/payment-result'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/admin/semesters/$id'
    | '/admin/semesters'
    | '/teacher/classes/$classSectionId/students'
    | '/admin/semesters/$id/classes/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/student'
    | '/teacher'
    | '/admin/academic-results'
    | '/admin/chat'
    | '/admin/class-sections'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/enrollments'
    | '/admin/exam-registrations'
    | '/admin/exam-schedules'
    | '/admin/homerooms'
    | '/admin/knowledge'
    | '/admin/majors'
    | '/admin/periods'
    | '/admin/profile'
    | '/admin/rooms'
    | '/admin/semesters'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/users'
    | '/student/academic-results'
    | '/student/chat'
    | '/student/course-registration'
    | '/student/curriculum'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/grades'
    | '/student/notifications'
    | '/student/payment-result'
    | '/student/profile'
    | '/student/retake-registration'
    | '/student/schedule'
    | '/student/tuition'
    | '/teacher/attendance'
    | '/teacher/chat'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/grades'
    | '/teacher/profile'
    | '/teacher/timetable'
    | '/admin/semesters/$id'
    | '/admin/semesters/'
    | '/teacher/classes/$classSectionId/students'
    | '/admin/semesters/$id_/classes/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/grades': {
      id: '/teacher/grades'
      path: '/grades'
      fullPath: '/teacher/grades'
      preLoaderRoute: typeof TeacherGradesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/chat': {
      id: '/teacher/chat'
      path: '/chat'
      fullPath: '/teacher/chat'
      preLoaderRoute: typeof TeacherChatRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/tuition': {
      id: '/student/tuition'
      path: '/tuition'
      fullPath: '/student/tuition'
      preLoaderRoute: typeof StudentTuitionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/retake-registration': {
      id: '/student/retake-registration'
      path: '/retake-registration'
      fullPath: '/student/retake-registration'
      preLoaderRoute: typeof StudentRetakeRegistrationRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payment-result': {
      id: '/student/payment-result'
      path: '/payment-result'
      fullPath: '/student/payment-result'
      preLoaderRoute: typeof StudentPaymentResultRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/curriculum': {
      id: '/student/curriculum'
      path: '/curriculum'
      fullPath: '/student/curriculum'
      preLoaderRoute: typeof StudentCurriculumRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course-registration': {
      id: '/student/course-registration'
      path: '/course-registration'
      fullPath: '/student/course-registration'
      preLoaderRoute: typeof StudentCourseRegistrationRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/chat': {
      id: '/student/chat'
      path: '/chat'
      fullPath: '/student/chat'
      preLoaderRoute: typeof StudentChatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/academic-results': {
      id: '/student/academic-results'
      path: '/academic-results'
      fullPath: '/student/academic-results'
      preLoaderRoute: typeof StudentAcademicResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/semesters': {
      id: '/admin/semesters'
      path: '/semesters'
      fullPath: '/admin/semesters'
      preLoaderRoute: typeof AdminSemestersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/periods': {
      id: '/admin/periods'
      path: '/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AdminPeriodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/majors': {
      id: '/admin/majors'
      path: '/majors'
      fullPath: '/admin/majors'
      preLoaderRoute: typeof AdminMajorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homerooms': {
      id: '/admin/homerooms'
      path: '/homerooms'
      fullPath: '/admin/homerooms'
      preLoaderRoute: typeof AdminHomeroomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exam-schedules': {
      id: '/admin/exam-schedules'
      path: '/exam-schedules'
      fullPath: '/admin/exam-schedules'
      preLoaderRoute: typeof AdminExamSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exam-registrations': {
      id: '/admin/exam-registrations'
      path: '/exam-registrations'
      fullPath: '/admin/exam-registrations'
      preLoaderRoute: typeof AdminExamRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/class-sections': {
      id: '/admin/class-sections'
      path: '/class-sections'
      fullPath: '/admin/class-sections'
      preLoaderRoute: typeof AdminClassSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic-results': {
      id: '/admin/academic-results'
      path: '/academic-results'
      fullPath: '/admin/academic-results'
      preLoaderRoute: typeof AdminAcademicResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/semesters/': {
      id: '/admin/semesters/'
      path: '/'
      fullPath: '/admin/semesters/'
      preLoaderRoute: typeof AdminSemestersIndexRouteImport
      parentRoute: typeof AdminSemestersRoute
    }
    '/admin/semesters/$id': {
      id: '/admin/semesters/$id'
      path: '/$id'
      fullPath: '/admin/semesters/$id'
      preLoaderRoute: typeof AdminSemestersIdRouteImport
      parentRoute: typeof AdminSemestersRoute
    }
    '/teacher/classes/$classSectionId/students': {
      id: '/teacher/classes/$classSectionId/students'
      path: '/$classSectionId/students'
      fullPath: '/teacher/classes/$classSectionId/students'
      preLoaderRoute: typeof TeacherClassesClassSectionIdStudentsRouteImport
      parentRoute: typeof TeacherClassesRoute
    }
    '/admin/semesters/$id_/classes/create': {
      id: '/admin/semesters/$id_/classes/create'
      path: '/$id/classes/create'
      fullPath: '/admin/semesters/$id/classes/create'
      preLoaderRoute: typeof AdminSemestersIdClassesCreateRouteImport
      parentRoute: typeof AdminSemestersRoute
    }
  }
}

interface AdminSemestersRouteChildren {
  AdminSemestersIdRoute: typeof AdminSemestersIdRoute
  AdminSemestersIndexRoute: typeof AdminSemestersIndexRoute
  AdminSemestersIdClassesCreateRoute: typeof AdminSemestersIdClassesCreateRoute
}

const AdminSemestersRouteChildren: AdminSemestersRouteChildren = {
  AdminSemestersIdRoute: AdminSemestersIdRoute,
  AdminSemestersIndexRoute: AdminSemestersIndexRoute,
  AdminSemestersIdClassesCreateRoute: AdminSemestersIdClassesCreateRoute,
}

const AdminSemestersRouteWithChildren = AdminSemestersRoute._addFileChildren(
  AdminSemestersRouteChildren,
)

interface AdminRouteChildren {
  AdminAcademicResultsRoute: typeof AdminAcademicResultsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminClassSectionsRoute: typeof AdminClassSectionsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminExamRegistrationsRoute: typeof AdminExamRegistrationsRoute
  AdminExamSchedulesRoute: typeof AdminExamSchedulesRoute
  AdminHomeroomsRoute: typeof AdminHomeroomsRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminMajorsRoute: typeof AdminMajorsRoute
  AdminPeriodsRoute: typeof AdminPeriodsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSemestersRoute: typeof AdminSemestersRouteWithChildren
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicResultsRoute: AdminAcademicResultsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminClassSectionsRoute: AdminClassSectionsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminExamRegistrationsRoute: AdminExamRegistrationsRoute,
  AdminExamSchedulesRoute: AdminExamSchedulesRoute,
  AdminHomeroomsRoute: AdminHomeroomsRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminMajorsRoute: AdminMajorsRoute,
  AdminPeriodsRoute: AdminPeriodsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSemestersRoute: AdminSemestersRouteWithChildren,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentAcademicResultsRoute: typeof StudentAcademicResultsRoute
  StudentChatRoute: typeof StudentChatRoute
  StudentCourseRegistrationRoute: typeof StudentCourseRegistrationRoute
  StudentCurriculumRoute: typeof StudentCurriculumRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPaymentResultRoute: typeof StudentPaymentResultRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRetakeRegistrationRoute: typeof StudentRetakeRegistrationRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentTuitionRoute: typeof StudentTuitionRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcademicResultsRoute: StudentAcademicResultsRoute,
  StudentChatRoute: StudentChatRoute,
  StudentCourseRegistrationRoute: StudentCourseRegistrationRoute,
  StudentCurriculumRoute: StudentCurriculumRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPaymentResultRoute: StudentPaymentResultRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRetakeRegistrationRoute: StudentRetakeRegistrationRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentTuitionRoute: StudentTuitionRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherClassesRouteChildren {
  TeacherClassesClassSectionIdStudentsRoute: typeof TeacherClassesClassSectionIdStudentsRoute
}

const TeacherClassesRouteChildren: TeacherClassesRouteChildren = {
  TeacherClassesClassSectionIdStudentsRoute:
    TeacherClassesClassSectionIdStudentsRoute,
}

const TeacherClassesRouteWithChildren = TeacherClassesRoute._addFileChildren(
  TeacherClassesRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherChatRoute: typeof TeacherChatRoute
  TeacherClassesRoute: typeof TeacherClassesRouteWithChildren
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherGradesRoute: typeof TeacherGradesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherChatRoute: TeacherChatRoute,
  TeacherClassesRoute: TeacherClassesRouteWithChildren,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherGradesRoute: TeacherGradesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
